### PR TITLE
New website design

### PR DESCRIPTION
**Pull request by muuvmuuv**
Did not tested it yet on all devices since docusaurus is not very easy to modify and I just wanted to share a clickable version of my design in #121.

Related issue: #120 
Related issue: #121

### CODE REVIEW

**Comment by muuvmuuv** [comment]
@Glavin001 What does that mean "This branch is out-of-date with the base branch". I think the branch is up to date. What do I have to do? Do I have to press "Update branch"? I‘m not a Git/GitHub pro…

**Comment by Glavin001** [comment]
BTW, since I previous said it in another chat and not here: **this is awesome 🎉 !!** Keep up the great work! Let me know if you need anything 😃

**Comment by muuvmuuv** [comment]
@Glavin001 the reason why I added all manually is that I was not sure how to implement them right. Normally I use SCSS to include only necessary parts of bootstrap (or any other library) but since Docusaurus are not supporting SCSS I added it myself. Sure in future that would be changed (js libs would also be placed in package.json)!

Why are there so many files in `/static`: the reason is that I tried to split modules/components and parts of the templates in different files like I would do in SCSS. It is great that Docusaurus is parsing all CSS files, so it is working fine.

I really tried to keep it small, but also clean and readable. I think it just looks like many files for you. If you would dive deeper into the structure I made, it would make more sense to you.

PS: agolia.css is an override, not the full CSS (that comes from Docusaurus btw.)

**Comment by muuvmuuv** [comment]
We should also update the stats. I don‘t know where you get them from, but maybe we can pull them on demand? So a script that updates a JSON file every 10minutes/days(?) and the website is parsing them. Just an idea.

**Comment by muuvmuuv** [comment]
Great, but I think for now CSS will work and fit.

Hm. Okay, I understand the reason of not merging that big PR, but how do I cut it down? Can I merge commits?

**Comment by szeck87** [comment]
@muuvmuuv where did you get the CSS and JS files under static?

**Comment by muuvmuuv** [comment]
@szeck87 what do you mean? I wrote the CSS and theme.js by myself, selectList.js and disqus.js are  @Glavin001 and the rest you can ignore because we will use CDN instead or npm packages

**Comment by Glavin001** [comment]
>  Can I merge commits?

Yes, you can [squash commits together with Git](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history#squash-commits-together). However, if you are unfamiliar with this functionality of Git, then I recommend create a fresh branch off of `master` then copying over the files you need and re-committing. Feel free to make a new PR and close this one if you do. Please be careful if you try to use Git Squash, as I would not want to lose all of this great progress! 😃 

> @szeck87 what do you mean? I wrote the CSS and theme.js by myself, selectList.js and disqus.js are @Glavin001 and the rest you can ignore because we will use CDN instead or npm packages

Sounds good 👍 . Looking forward to seeing it 🎉 .

**Comment by muuvmuuv** [comment]
Ok, I‘ll make a new PR. Closing this one

**Pull request closed without merging**
