### PR TITLE
Improvements and bug fixes 

### PR DESCRIPTION
**Pull request by muuvmuuv**
Fixed a bug with featherlight on doc pages and made some improvements to the UI (mostly responsive issues).

### CODE REVIEW

**Comment by muuvmuuv** [comment]
@Glavin001 how can I modify the Unibeautify bot to beautify the files like my VSCode extension does it? It is annoying that they both are thinking differently about beautification.

**Comment by Glavin001** [comment]
>  how can I modify the Unibeautify bot to beautify the files like my VSCode extension does it?

It should already. Please provide specific examples of cases where it is not, and what you expect.

**Comment by szeck87** [comment]
@muuvmuuv The bot bases the beautification based on the configuration for the repo's [.unibeautifyrc.yml](https://github.com/Unibeautify/website/blob/master/.unibeautifyrc.yml) file. Are you using a different configuration when editing in VSCode?

**Comment by muuvmuuv** [comment]
@szeck87 nope. That is why I'm so confused. It removes the whitespace between `>` characters in the CSS, where my Unibeautify VSCode extension does not.

**Comment by szeck87** [comment]
It's definitely JSBeautify that is removing those spaces.  In VSCode, the beautifiers are ordered:

1. Prettier
2. JSBeautify
3. Pretty Diff

So Pretty Diff re-adds those spaces.  I can't see the details for Unibeautify CI, but I'm guessing JSBeautify is the last one being run there.  @Glavin001 would have to confirm.

You could modify the `.unibeautifyrc.yml` file to include beautifiers under CSS in a different order:

`beautifiers: ["JS-Beautify", "Pretty Diff", "Prettier"]`

**Comment by Glavin001** [comment]
> I can't see the details for Unibeautify CI, but I'm guessing JSBeautify is the last one being run there.

@szeck87 Correct:

```
export const beautifiers: Beautifier[] = <any[]>[
  prettier,
  prettyDiff,
  jsBeautify,
  eslint,
  phpCsFixer,
];
```

Unibeautify should really require `beautifiers`. It is missing in `CSS` right now: https://github.com/Unibeautify/website/blob/master/.unibeautifyrc.yml#L24
It should throw an error encouraging users to add `beautifiers` 🤔 .

**Comment by Glavin001** [comment]
@muuvmuuv could you include before / after screenshots? This helps for where we should look and interact, and also a quick way to review the change from a visual level -- can even be reviewed and discussed while I'm on my phone 😜 . Thank you!

**Comment by Glavin001** [comment]
@szeck87 Looks like this line is causing the above confusion: https://github.com/Unibeautify/unibeautify/blob/master/src/beautifier.ts#L336
🔥.

Do you agree we should change this in Unibeautify core? If so, I'll make a PR tomorrow. I have a couple other changes I'd like to add in a little PR while I'm at it 😄 .

**Comment by muuvmuuv** [comment]
@Glavin001 Here are the Before and After screenshots. And I have noticed why Unibeautify CI is fixing those CSS "issues". I'm using a separate formatter for CSS (CSSComb). Can I add it to the vscode settings to disable it for this project?

Menu before:
screenshot 2018-08-29 at 09 25 12

Menu after:
screenshot 2018-08-29 at 09 26 22

Hero before:
screenshot 2018-08-29 at 09 27 29

Hero after:
screenshot 2018-08-29 at 09 26 44

Bottom navigation before:
screenshot 2018-08-29 at 09 27 53

Bottom navigation after:
screenshot 2018-08-29 at 09 28 12

**Comment by Glavin001** [comment]
@muuvmuuv Screenshot improvements look great! Awesome work!

**Comment by Glavin001** [comment]
> I'm using a separate formatter for CSS (CSSComb)

Did you implement a CSSComb beautifier for Unibeautify? If so, could you submit a PR to https://github.com/Unibeautify/beautifier-csscomb ? Then we can add official support 🎉

**Comment by muuvmuuv** [comment]
@Glavin001  not yet, I had not enough time to dig into the execution part for CSSComb as it is not a node library... but I'm searching for alternatives that also provide sort-order!
I'll try to turn it off for this workspace and use prettier instead.

**Comment by muuvmuuv** [comment]
@Glavin001 It seems there is a error on the Unibeautify CI and it seems I can not close issues when commiting "close hash number".

**Comment by Glavin001** [comment]
> it seems I can not close issues when commiting "close hash number".

Needs to be merged into default branch (i.e. `master`) to actually trigger close of issue.

**Pull request merged**
