### PR TITLE
Close #9. Add email signup with waitlist

### PR DESCRIPTION
**Pull request by Glavin001**
Close #9. Add email signup with waitlist

# Before sign up

image

# After sign up

image

### CODE REVIEW

**Comment by Glavin001** [comment]
Whoops #9 is the wrong issue.

**Comment by szeck87** [comment]
What is this sign-up for?  I would add some context around what users sign up for.

**Comment by Glavin001** [comment]
Good question. At this point, I simply wanted to track interested users.

**Comment by Glavin001** [comment]
How about "Sign up for early access"

image

**Pull request merged**
