### PR TITLE
Add install link to Unibeautify CI

### PR DESCRIPTION
**Pull request by Glavin001**
https://github.com/apps/unibeautify-ci

---

# Nav Bar

| Before | After |
| --- | --- |
| image | image |

# Landing

| Before | After |
| --- | --- |
| image | image |

# GitHub

| Before | After |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by muuvmuuv** [comment]
Great! Did you test mobile responsiveness?

**Comment by Glavin001** [comment]
@muuvmuuv Oh no I did not test mobile yet 😱.

**Comment by muuvmuuv** [comment]
@Glavin001 looks great in mobile too. Just wanted to make sure one more menu item is not breaking the UI, but Docusaurus implemented a horizontal scroll menu so it is no problem to add more!

**Comment by Glavin001** [comment]
Thanks for checking @muuvmuuv ! I really appreciate your 👁 for good UI/UX 😃 .

Any feedback for https://github.com/apps/unibeautify-ci before this is merged?

**Comment by muuvmuuv** [comment]
@Glavin001 Looks good! I would give that images a shadow and border like the big box has on our website. Just to better separate the text and images. The first image's text really got me confused. Or maybe make an intro GIF/Video to visualize a short process. Also, we need to change the logo everywhere when we continue using it on the website. This should be consistent!

**Comment by muuvmuuv** [comment]
btw! This is really good work from you and Steven! I'm happy to be partly involved, this is something I had really missing in GitHub. Did you thought about an implementation to GitLab/Bitbucket or is this already possible with the CLI? Just asking, because I would love to use it in our company internally.

**Comment by Glavin001** [comment]
> I would give that images a shadow and border like the big box has on our website. Just to better separate the text and images.

@muuvmuuv How's this? https://github.com/apps/unibeautify-ci

| Before | After |
| --- | --- |
| image | image |

>  Or maybe make an intro GIF/Video to visualize a short process. 

I'd like to add a video soon. I have some more improvements I'd like to add first.

> This is really good work from you and Steven!

Thank you! Many years in the making with a lot of help from the open-source community. Glad it will be useful 😃 .

> Did you thought about an implementation to GitLab/Bitbucket or is this already possible with the CLI?

Possible with CLI although not idea. I would like to support GitLab and BitBucket, however, I need more time to develop.

> I would love to use it in our company internally.

Which are you using? Maybe you could be the first tester once I'm ready 😜 .

**Comment by Glavin001** [comment]
I just added links to Atom-Beautify's README 🎉 .
https://github.com/Glavin001/atom-beautify

**Comment by muuvmuuv** [comment]
@Glavin001  This looks neat! You should maybe get used to GitHubs Todos Tab. To track those features milestones? Would be nicer for you and us to see the progress and what is already in the making and what in the backlog :)

We are using GitLab CE and I'm using Bitbucket for private projects, so I could test both once your ready ^^

**Comment by muuvmuuv** [comment]
And I would likely say we should make an "Update to Unibeautify now!" banner on the atom-beautify page once its ready without heavy bugs. And maybe display those in atom a message with "Hey, we love to see you are still using our awesome tool to make code looking nice and pretty. We have launched an improved version called Unibeautify and it's ready to download! Check it out and also have a look at our CI tool!"

**Pull request merged**
