### PR TITLE
Add sqlformat

### PR DESCRIPTION
**Pull request by szeck87**
Adds sqlformat to website

### CODE REVIEW

**Comment by Glavin001** [comment]
You'll need to edit https://github.com/Unibeautify/website/blob/master/scripts/netlify.sh#L7 to add https://github.com/andialbrecht/sqlparse I think.

**Comment by Glavin001** [comment]
Awesome, thanks @szeck87 !

**Comment by szeck87** [comment]
I just noticed there is a separate script in package.json to update the README.

**Comment by Glavin001** [comment]
Oops forgot about the README: https://github.com/Unibeautify/website#supported-beautifiers 

Should add some check to CI for README diff.

**Pull request merged**
